### ISSUE TITLE
Spelling - Line 106

### ISSUE THREAD

**Issue by GarethSharpe** [cp317/Website#11]
Line 106 reads: "... which can be used to sort for location, school name, and course code." 

Suggested Solution: "... which can be used to sort based on location, school name, and course code."

Line 106 reads: "...displaying boxes showing detailed information all the nearby..."

Suggested Solution: "...displaying boxes showing detailed information of all the nearby..."

Line 106 reads: "These bozes will be ordered by..."

Suggested Solution: "These boxes will be ordered by..."

**Comment by ghost** [comment]
Replaced with suggested solution
