### ISSUE TITLE
Requirements document dynamic section numbers

### ISSUE THREAD

**Issue by Jake-L** [cp317/Website#34]
David Brown would like the section numbers to be dynamic using html. 

For example, right now we set up the table of contents like:
`<li><a href="#1.3">1.3 Document Lexicon</a></li>`

And we display that header as:
`<span id="1.3">1.3 Document Lexicon</span>`

And David Brown would like that code to not include any hard-coded section numbers.

Paging documentation team:
@shiv24 @ayang0302 @lunaticdudette97 @JasmaanPanesar @orchidami 

We will need to do this for every document, so it would be good to get it done for the requirements document so that all the other docs can just re-use the code.

**Comment by ayang0302** [comment]
Check out the latest analysis html file with these changes, the similar changes will be made to requirements and eventually design. Closing issue.
