### ISSUE TITLE
The analysis document is not consistent  with the requirement document

### ISSUE THREAD

**Issue by TrysFU** [cp317/Website#36]
There are more than 4 entity objects defined in the analysis document, but there is only 4 such items mentioned in the requirement document.

https://github.com/cp317/Website/blob/d9b57bae29a4f86fb5e7251033076f730a7332bb/analysis/analysis.html#L42-L48

Note that anything that is an entity object would be essentially stored in the database in a table. So if the information is not being saved in the database, it should not be part of the entity objects.

Possible solution:
I do not see why we must have a Host object, Guest object, and a profile object where the user object can have attributes to ensure those functionalities are met. 
Also the Beacon object will have a table in the database so there is absolutely no need for a BeaconList object.

**Comment by bbogusat** [comment]
@TrysFU - Please take a look at the changes and let me know what you think.
