### ISSUE TITLE
Design issue for boundary and control objects

### ISSUE THREAD

**Issue by TrysFU** [cp317/Website#38]
If I have counted correctly, currently there are 15 boundary objects (i.e number of views which would be the number of different html files) and there are 16 control objects. I do not see why one boundary object would need more than one control object. Also the naming does not help with which boundary object belongs to which control object.

https://github.com/cp317/Website/blob/d9b57bae29a4f86fb5e7251033076f730a7332bb/analysis/analysis.html#L50-L84

Possible solution:
Each boundary object should have exactly one control object with all functionalities included in the control object and the naming convention should indicate exactly which control object belongs to which boundary object for clarity.

**Comment by bbogusat** [comment]
Ignore that message. Had a naming issue. That is actually #36.

**Comment by bbogusat** [comment]
@TrysFU I do disagree that the number of control objects should equal the boundary objects.  Control objects can go Control -> Control in some instances so I don't believe having equal numbers should be a requirement. I'm open to hearing your thoughts though if you disagree still.

I do agree with clearer naming and I'll get on that. :) 

Think of the control objects as the choice the user makes. Reference the  Beacon Control Diagram for an example. [https://github.com/cp317/Website/blob/master/analysis/diagrams/Robustness__BeaconControl.png](url)
